//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblBooking
    {
        public int Booking_ID { get; set; }
        [Required(ErrorMessage = "customer id is must")]
        public string Customer_ID { get; set; }
        [Required(ErrorMessage = "hotelid is must")]
        public string HotelID { get; set; }
        [Required(ErrorMessage = "bookingdate is must")]
        public System.DateTime BookingDate { get; set; }
        [Required(ErrorMessage = "arrivaldate is must")]
        public System.DateTime ArrivalDate { get; set; }
        [Required(ErrorMessage = "departuredate is must")]
        public System.DateTime DepartureDate { get; set; }
        [Required(ErrorMessage = "number of adults is must")]
        public int Number_of_Adults { get; set; }
        [Required(ErrorMessage = "number of children is must")]
        public int Number_of_Children { get; set; }
        [Required(ErrorMessage = "number of nights is must")]
        public int Number_of_Nights { get; set; }
        [Required(ErrorMessage = "roomtype is must")]
        public string Room_Type { get; set; }
        [Required(ErrorMessage = "number of rooms is must")]
        public int Number_of_Rooms { get; set; }

        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblHotelDetail tblHotelDetail { get; set; }
    }
}
