//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblHotelDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHotelDetail()
        {
            this.tblBookings = new HashSet<tblBooking>();
        }
        [Required(ErrorMessage = "HotelId is must")]
        [RegularExpression("^[W]{1}[O]{1}[W]{1}[1-9]{4}$", ErrorMessage = "HotelId is in incorrect format")]
        public string HotelID { get; set; }

        [Required(ErrorMessage = "HotelName is must")]
        [RegularExpression("^[a-z]{1,20}$", ErrorMessage = "HotelName is in incorrect format")]
        public string Hotel_Name { get; set; }
        [Required(ErrorMessage = "Country is must")]
        public string Country { get; set; }
        [Required(ErrorMessage = "City is must")]
        public string City { get; set; }
        [Required(ErrorMessage = "HotelDescription is must")]
        public string Hotel_Description { get; set; }
        [Required(ErrorMessage = "No of Ac Rooms is must")]
        [Range(1, 300, ErrorMessage = "No of Ac Rooms must be  between 1 and 300")]
        public int Number_of_AC_Rooms { get; set; }
        [Required(ErrorMessage = "No of NonAc is Rooms must")]
        [Range(1, 300, ErrorMessage = "No of Non-Ac Rooms must be between 1 and 300")]
        public int Number_of_Non_AC_Rooms { get; set; }
        [Required(ErrorMessage = "This Field Is Required")]
        [Range(2001, 3000, ErrorMessage = "Rate for a Child for one Ac Room must be between 2001 and 3000")]
        public int Rate_for_one_night_for_one_children_AC { get; set; }
        [Required(ErrorMessage = "This Field Is Required")]
        [Range(2501, 4000, ErrorMessage = "Rate for an  Adult for one Ac Room must be between 2501 and 4000")]
        public int Rate_for_one_night_for_one_adult_AC { get; set; }
        [Required(ErrorMessage = "This Field Is Required")]
        [Range(1000, 2000, ErrorMessage = "Rate for a Child for one Non-Ac Room must be  between 1000 and 2000")]
        public int Rate_for_one_night_for_one_children_NONAC { get; set; }
        [Required(ErrorMessage = "This Field Is Required")]
        [Range(2000, 2500, ErrorMessage = "Rate for an Adult for one Non-Ac Room must be  between 2000 and 2500")]
        public int Rate_for_one_night_for_one_adult_NONAC { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBooking> tblBookings { get; set; }
    }
}
